apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-offh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-offh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-offh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-offh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-offh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qzlv-tenant/rhtap-demo-app/hacbs-test-project-offh@sha256:22f8f771cf807ccafaa1f1be4dae87430794c7baddae28fc29f2d59db2237488
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
